on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write
  deployments: write
  issues: write
  packages: write
  pages: write
  repository-projects: write
  security-events: write
  statuses: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
